// Ordleg baked-art manifest (Liveliness PRD-10 §3.2). One soft-3D WebP per concrete word-picture,
// keyed by the word's stable ASCII `art` id (the shared word-picture set — see §4), theme-CONSTANT
// (one set reused across all 4 skins, like the section icons), generated by the owner in Gemini on a
// `#00FF00` green screen and keyed with the `sharp` pipeline (`.claude/rules/scene-assets.md`).
// Copied from src/assets/games/math/index.ts (the id-keyed variant).
//
// WORDS + LETTERS ARE NOT ART (§0.4): the uppercase prompt WORD (Læs Ordet), the letter tiles + slots
// (Stav Ordet), and the spelled-out letters (Sig et Ord) stay Comic Sans Typography — recognising /
// reading / spelling the glyphs IS the exercise. Only the *depicted picture* (the cow/car/cat) is
// baked. Abstract words with no clean depiction (hej/arm/ben/fod/hul/mor/far) have no art id → they
// keep their emoji via the art-gated fallback.
//
// The `art` id is ALREADY ASCII (aeg/raev/baer/loeg/aal/soe for æg/ræv/bær/løg/ål/sø — the Danish
// glyphs are filesystem-awkward), so the filename stem === the art id directly: no glyph-alias map is
// needed (unlike the alphabet loader, which keys by the raw glyph). Filenames are the art id, e.g.
// `kat.webp`, `aeg.webp`, `raev.webp`.
//
// ART-GATED (PRD-06/-10): this globs whatever WebP the owner has dropped into THIS directory. Until
// the batch lands the manifest is empty and `ordlegArt()` returns `undefined`, so every consumer
// (Læs Ordet answer pictures, Stav Ordet prompt picture, Sig et Ord match-bloom) keeps its emoji
// fallback. Drop the keyed files and they auto-register with no code change. One image per id;
// ≤40 KB, square, transparent (per scene-assets rules).

import { sharedArtMap } from '../shared'
import { englishArtMap } from '../english'

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// word art id → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const ordlegArtMap: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  ordlegArtMap[stem] = url
}

// The baked soft-3D subject for a word art id, or `undefined`. Concrete Ordleg words resolve from
// THIS dir; the 7 abstract words reuse cross-section art (PRD-12 Phase B): arm/ben/fod/mor/far →
// the SHARED pool (`../shared`), hej → `hello` in the ENGLISH greetings dir, hul → this dir. So it
// falls back ordleg → shared → english. Every Ordleg word is now baked — the emoji fallback is gone.
export const ordlegArt = (id: string | undefined): string | undefined =>
  id ? ordlegArtMap[id] ?? sharedArtMap[id] ?? englishArtMap[id] : undefined

export default ordlegArtMap
