// Game subject art root + loader (Liveliness PRD-06 F5). Pictorial prompt/object subjects across
// the games (the apple, counting objects, colour objects, English vocab, …) become baked soft-3D
// WebP — theme-CONSTANT (one set reused across all 4 skins, like the section icons / game icons),
// generated by the owner in Gemini on a `#00FF00` green screen and keyed with the existing `sharp`
// pipeline (`.claude/rules/scene-assets.md`). GLYPHS ARE NOT ART: letters/numerals stay Typography
// (recognising the letterform / numeral IS the lesson) — only *depicted things* are baked.
//
// Each section supplies its own manifest module under `src/assets/games/<section>/index.ts`
// (content id → hashed WebP URL) and registers a loader below. This mirrors `theme/sceneAssets.ts`:
// per-section dynamic import so Vite code-splits each area's art, and a failed/absent load degrades
// to `null` (never throws). ART-GATED: the Foundation ships ZERO art — the registry is empty and
// every load resolves to `null` until an area PRD lands its keyed WebP batch and registers it here.

export type GameSection = 'alphabet' | 'math' | 'colors' | 'english' | 'ordleg'

// content id (e.g. a letter, a colour-object id, an English word) → ready-to-render WebP URL.
export type GameArtManifest = Record<string, string>

// Populated per area (art-gated). Register a section once its batch is keyed + wired, e.g.:
//   alphabet: () => import('./alphabet'),
const loaders: Partial<Record<GameSection, () => Promise<{ default: GameArtManifest }>>> = {}

// Resolve a section's baked game-art manifest, or `null` if the section has none yet.
// Never throws: a missing/failed import degrades to `null` (the caller keeps its emoji/glyph path).
export async function loadGameArt(section: GameSection): Promise<GameArtManifest | null> {
  const loader = loaders[section]
  if (!loader) return null
  try {
    return (await loader()).default
  } catch {
    return null
  }
}

// Whether a section has registered game art (without fetching it).
export const hasGameArt = (section: GameSection): boolean => section in loaders
