// Farver baked-art manifest (Liveliness PRD-09 §3.1). One soft-3D WebP per curated colour-object,
// keyed by the object's stable `art` id (see the `art` field on `ColorObject` in
// src/config/colorContent.ts), theme-CONSTANT (one set reused across all 4 skins, like the section
// icons), generated by the owner in Gemini on a `#00FF00` green screen and keyed with the `sharp`
// pipeline (`.claude/rules/scene-assets.md`). Copied from src/assets/games/math/index.ts.
//
// COLOURS ARE NOT ART: the mixing droplets, colour swatches, and shade tiles stay pure-hex DATA
// (COLOR_SWATCH / SHADES / primaryColors) — the colour IS the lesson. Only the *depicted objects*
// (apple/car/whale/…) are baked, and each is baked in its hue's TRUE colour so it reads correct with
// no coloured backing tile.
//
// ART-GATED (PRD-06/-09): this globs whatever WebP the owner has dropped into THIS directory. Until
// the batch lands the manifest is empty and `colorObjectArt()` returns `undefined`, so every consumer
// (Farvejagt objects, Hvilken Farve? dragged object, Lær Farver examples) keeps its emoji fallback.
// Drop the keyed files and they auto-register with no code change — filenames are the object art id,
// e.g. `apple.webp`, `whale.webp`, `crystal.webp` (all ASCII → no aliasing). One image per id;
// ≤40 KB, square, transparent (per scene-assets rules).

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// object art id → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const farverArt: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  farverArt[stem] = url
}

// The baked soft-3D subject for a colour-object art id, or `undefined` (→ caller keeps its emoji
// fallback). `id` is the `art` field on a `ColorObject` (undefined-safe: returns undefined for a
// missing/absent id).
export const colorObjectArt = (id: string | undefined): string | undefined =>
  id ? farverArt[id] : undefined

export default farverArt
