// GENERATED by scripts/bake-music.mjs — do not edit. Re-run `npm run music:bake` instead.
// What each shipped public/sounds/music/<world>.mp3 was baked to; musicLevel.test.ts checks it.
export const MUSIC_BAKED_TARGET_LUFS = -38

export const MUSIC_BAKED: Record<string, { sha256: string; lufs: number }> = {
  dino: { sha256: 'f950fc1350ea8da4ff68a7c98e4e1bf8896136298551c194249cfeeae9891bd0', lufs: -38.4 },
  kid: { sha256: 'f40d7795d0a94351725f3c39ecbf92ead789be64e145d83749497d0fdd2945a1', lufs: -38.4 },
  ocean: { sha256: '592dca57f301f7754c292ac2d58c6242f883fe588d34505f951d6f1ed4c2b061', lufs: -38.4 },
  space: { sha256: 'f2424a847e4039c6fcbef03780723ccd27cad5bc5fe0bdde015a7006d7077bca', lufs: -38.4 },
}
