// Reward Book baked-art manifest (Reward Book PRD-01 §6/W0). One soft-3D WebP per reward on the
// path, keyed by the reward's stable ASCII id (`dyr-hund`, `kt-bil`, `mad-aeble`, …), theme-CONSTANT
// (one set reused across all 4 skins, like the section icons), generated by the owner in Gemini on a
// `#00FF00` green screen and keyed with the `sharp` pipeline (`.claude/rules/scene-assets.md`).
// Follows the same glob-manifest shape as src/assets/games/ordleg/index.ts.
//
// ART-GATED (PRD D4): this globs whatever WebP has been dropped into THIS directory. Until the batch
// lands the manifest is empty and `rewardArt()` returns `undefined`, so every consumer (the corner
// RewardRing silhouette, the book slots, the ceremony's StickerReveal, the home shelf, the result
// meter) falls back to the reward's emoji. Drop the keyed files and they auto-register with no code
// change — chapter by chapter, if that's how they arrive. One image per id; 256×256, ≤20 KB,
// square + trimmed, transparent (per scene-assets rules).
//
// NB this module is Vite-only (`import.meta.glob`). `src/config/stickers.ts` deliberately does NOT
// import it, because shared-narration-clips.js imports that file in plain Node — see the note there.

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// reward id → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const rewardArtMap: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  rewardArtMap[stem] = url
}

// The baked soft-3D render for a reward id, or `undefined` while the art is still pending.
export const rewardArt = (id: string | undefined): string | undefined =>
  id ? rewardArtMap[id] : undefined

export default rewardArtMap
