// Baked child-profile avatar art (de-emoji PRD-01). One soft-3D head-and-shoulders portrait per
// avatar id, theme-CONSTANT (one set across all 4 skins, like the section icons), generated by the
// owner in Gemini on a `#00FF00` green screen and keyed by
// `node scripts/optimize-theme-art.mjs avatars` (see `.claude/rules/scene-assets.md`).
//
// Portraits rather than the usual 3/4 full-body subject, because these render inside a 44–64px
// circular badge where a full body is an unreadable blob.
//
// The id list itself lives in `src/config/avatars.ts` (pure, Node-importable, shared with
// `api/profiles.ts`); this module is Vite-only, so nothing server-side may import it.
// `avatars.test.ts` asserts the two stay in sync — every id in the closed set has art here.

const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// avatar id → ready-to-render WebP URL.
export const avatarArtMap: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  avatarArtMap[stem] = url
}

// The baked portrait for an avatar id. Unlike `rewardArt`, this is NOT art-gated — the full set
// ships, and `avatars.test.ts` fails the build if one goes missing, so callers can render it
// unconditionally instead of carrying a fallback (PRD D5: never fall back to a glyph).
export const avatarArt = (id: string): string | undefined => avatarArtMap[id]

export default avatarArtMap
