// Bake the music bed's loudness into the shipped files (see src/config/musicLevel.ts for WHY:
// iOS ignores HTMLMediaElement.volume, so a runtime volume never reaches the iPad).
//
// For each master in art-src/music/*.mp3: measure its integrated loudness (EBU R128), apply the
// gain that lands it on musicTargetLufs(world) (MUSIC_TARGET_LUFS + any per-world trim), encode MP3
// into public/sounds/music/, re-measure, and
// record hash + measured LUFS in src/config/musicBaked.ts (the guard test reads that file).
//
// Usage:  npm run music:bake
// Requires the ffmpeg-static devDependency.

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import ffmpegPath from 'ffmpeg-static'

const run = promisify(execFile)
const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = path.join(ROOT, 'art-src', 'music')
const OUT_DIR = path.join(ROOT, 'public', 'sounds', 'music')
const BAKED_TS = path.join(ROOT, 'src', 'config', 'musicBaked.ts')

const { MUSIC_TARGET_LUFS: TARGET, musicTargetLufs } = await import('../src/config/musicLevel.ts')

async function measureLufs(file) {
  // ebur128 prints its summary on stderr; execFile resolves with it.
  const { stderr } = await run(
    ffmpegPath,
    ['-hide_banner', '-nostats', '-i', file, '-af', 'ebur128=framelog=quiet', '-f', 'null', '-'],
    { maxBuffer: 16 * 1024 * 1024 },
  )
  const hit = stderr.match(/I:\s+(-?\d+(?:\.\d+)?) LUFS/)
  if (!hit) throw new Error(`no loudness reading for ${file}`)
  return Number(hit[1])
}

await mkdir(OUT_DIR, { recursive: true })
const masters = (await readdir(SRC_DIR)).filter((f) => f.endsWith('.mp3')).sort()
if (!masters.length) {
  console.error(`No masters in ${SRC_DIR}`)
  process.exit(1)
}

const baked = {}
for (const file of masters) {
  const world = file.replace(/\.mp3$/, '')
  const src = path.join(SRC_DIR, file)
  const out = path.join(OUT_DIR, file)
  const before = await measureLufs(src)
  const gain = musicTargetLufs(world) - before
  // 128 kbps is ample for a bed sitting ~13 LU under the narration (masters are 256).
  await run(ffmpegPath, [
    '-y', '-loglevel', 'error', '-i', src,
    '-af', `volume=${gain.toFixed(2)}dB`,
    '-map_metadata', '-1', '-c:a', 'libmp3lame', '-b:a', '128k', out,
  ])
  const after = await measureLufs(out)
  const sha256 = createHash('sha256').update(await readFile(out)).digest('hex')
  baked[world] = { sha256, lufs: after }
  console.log(`  ${world}: ${before} → ${after} LUFS (gain ${gain.toFixed(2)} dB)`)
}

const body = Object.entries(baked)
  .map(([w, b]) => `  ${w}: { sha256: '${b.sha256}', lufs: ${b.lufs} },`)
  .join('\n')
await writeFile(
  BAKED_TS,
  `// GENERATED by scripts/bake-music.mjs — do not edit. Re-run \`npm run music:bake\` instead.\n` +
    `// What each shipped public/sounds/music/<world>.mp3 was baked to; musicLevel.test.ts checks it.\n` +
    `export const MUSIC_BAKED_TARGET_LUFS = ${TARGET}\n\n` +
    `export const MUSIC_BAKED: Record<string, { sha256: string; lufs: number }> = {\n${body}\n}\n`,
)
console.log(`\nBaked ${masters.length} tracks to ${TARGET} LUFS → public/sounds/music/, record in src/config/musicBaked.ts`)
