// Alphabet baked-art manifest (Liveliness PRD-07 §3.1). One soft-3D WebP per letter, keyed by the
// letter — the letter's example subject (A = Abe/monkey, B = Bil/car, …), theme-CONSTANT (one set
// reused across all 4 skins, like the section icons), generated by the owner in Gemini on a `#00FF00`
// green screen and keyed with the `sharp` pipeline (`.claude/rules/scene-assets.md`).
//
// GLYPHS ARE NOT ART: the letterform stays Typography everywhere (recognising the letter IS the
// lesson) — only the *depicted subject* is baked. Q/W/X/Å are intentionally picture-less (owner
// decision — glyph-only), so they never get a file here.
//
// ART-GATED (PRD-06/-07): this globs whatever WebP the owner has dropped into THIS directory. Until
// the batch lands the manifest is empty and `letterArt()` returns `undefined`, so every consumer
// (Bogstav Quiz hero, Lær Alfabetet bloom, Hukommelse card) keeps its emoji/glyph fallback. Drop the
// keyed files and they auto-register with no code change — filenames are the letter, e.g. `A.webp` …
// `Z.webp`, and for the Danish specials either the raw glyph (`Æ.webp`/`Ø.webp`) or the ASCII alias
// (`AE.webp`/`OE.webp`). One image per letter; ≤40 KB, square, transparent (per scene-assets rules).

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// ASCII-alias filenames → the canonical Danish glyph key (raw-glyph filenames pass through as-is).
const STEM_ALIASES: Record<string, string> = { AE: 'Æ', OE: 'Ø', AA: 'Å' }
const stemToLetter = (stem: string): string => {
  const up = stem.toUpperCase()
  return STEM_ALIASES[up] ?? up
}

// letter → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const alphabetArt: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  alphabetArt[stemToLetter(stem)] = url
}

// The baked soft-3D subject for a letter, or `undefined` (→ caller keeps its emoji/glyph fallback).
export const letterArt = (letter: string): string | undefined => alphabetArt[letter]

export default alphabetArt
