// English baked-art manifest (Liveliness PRD-11 §3.2). One soft-3D WebP per English-word-picture,
// keyed by the word's ASCII `art` id derived from the English word (`englishArtId`), theme-CONSTANT
// (one set reused across all 4 skins, like the section icons), generated by the owner in Gemini on a
// `#00FF00` green screen and keyed with the `sharp` pipeline (`.claude/rules/scene-assets.md`).
// Copied from src/assets/games/ordleg/index.ts (the id-keyed variant).
//
// WORDS + CAPTIONS ARE NOT ART (§0.4): the English WORD on the answer tiles (Find det Engelske Ord,
// Dansk til Engelsk) and the Danish caption under the Translate prompt stay Comic Sans Typography —
// reading the English word IS the lesson; the caption is a scaffold. Only the *depicted picture*
// (the dog/car/apple) is baked. Abstract words with no clean depiction (greetings) and — by owner
// decision — people/body words (family/body) have no art id file → they keep their emoji via the
// art-gated fallback automatically.
//
// The `art` id is COMPUTED from the English word via `englishArtId(en)` (lowercase, ASCII-only), so
// `"ice cream"` → `icecream`; every other concrete word is already a single ASCII token. No edit to
// `englishVocab.ts` is needed (no `art` field on `EnglishWord`). Filenames are the art id, e.g.
// `dog.webp`, `icecream.webp`, `car.webp`.
//
// ART-GATED (PRD-06/-11): this globs whatever WebP the owner has dropped into THIS directory. Until
// the batch lands the manifest is empty and `englishArt()` returns `undefined`, so every consumer
// (Lyt og Find answer pictures, Word/Translate prompt pictures, Lær Engelsk bloom + cards) keeps its
// emoji fallback. Drop the keyed files and they auto-register with no code change. One image per id;
// ≤40 KB, square, transparent (per scene-assets rules).

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// word art id → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const englishArtMap: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  englishArtMap[stem] = url
}

// Derive the stable ASCII art id from an English word: lowercase, strip anything non-alphanumeric
// (so `"ice cream"` → `icecream`, `"good morning"` → `goodmorning`). Consumers call
// `englishArt(englishArtId(w.en))`; never-baked words just have no file → `englishArt` returns
// undefined and the caller keeps its emoji fallback.
export const englishArtId = (en: string): string =>
  en.toLowerCase().replace(/[^a-z0-9]/g, '')

// The baked soft-3D subject for a word art id, or `undefined` (→ caller keeps its emoji fallback).
export const englishArt = (id: string | undefined): string | undefined =>
  id ? englishArtMap[id] : undefined

export default englishArtMap
