// Math baked-art manifest (Liveliness PRD-08 §3.1). One soft-3D WebP per shared counting object
// (apple/balloon/star/flower/car/ball/bird/fish — see src/config/countingObjects.ts),
// theme-CONSTANT (one set reused across all 4 skins, like the section icons), generated by the owner
// in Gemini on a `#00FF00` green screen and keyed with the `sharp` pipeline
// (`.claude/rules/scene-assets.md`). Copied from src/assets/games/alphabet/index.ts.
//
// GLYPHS ARE NOT ART: numerals stay Typography everywhere (recognising the number IS the lesson) —
// only the counted manipulatives are baked. The operators `+ − = ? > <` are already baked as
// SymbolTile art (src/assets/symbols) and are NOT part of this manifest.
//
// The Sammenlign `crocodile` was here too and was DELETED 2026-08-03 with the game's board rework
// (owner). It was supposed to teach `>`/`<` as a mouth eating the bigger number and did the reverse:
// mouth-closed art that was never mirrored, so it lunged tail-first at the bigger number on half of
// all questions. The symbol slot carries that meaning now — see ComparisonGame's header.
//
// ART-GATED (PRD-06/-08): this globs whatever WebP the owner has dropped into THIS directory. Until
// the batch lands the manifest is empty and `countingObjectArt()` returns `undefined`, so every
// consumer (today: the numbers Memory cluster via `artForObject`) keeps its glyph fallback. Drop the
// keyed files and they auto-register with no code change — filenames are the object id, e.g.
// `apple.webp`, `star.webp` (all filesystem-safe → no ASCII aliases). One image per id; ≤40 KB,
// square, transparent (per scene-assets rules).

// Statically-bundled URLs for every WebP in this folder (Vite rewrites each to its hashed asset URL).
const modules = import.meta.glob('./*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

// object id → ready-to-render WebP URL. Empty until the art batch is dropped in (art-gated).
export const mathArt: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const stem = path.split('/').pop()!.replace(/\.webp$/i, '')
  mathArt[stem] = url
}

// The baked soft-3D subject for a counting-object id, or `undefined` (→ caller keeps its fallback).
export const countingObjectArt = (id: string): string | undefined => mathArt[id]

export default mathArt
